### ISSUE TITLE
Invalid appdata.xml

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/Publish-AppImage#6]
If I build using your `appdata.xml` template, I get these warnings and errors:

```
W: hanumaninstitute.Player432hz:3: cid-desktopapp-is-not-rdns hanumaninstitute.Player432hz
I: hanumaninstitute.Player432hz:11: description-first-para-too-short
No description available.
E: hanumaninstitute.Player432hz:~: desktop-app-launchable-missing
I: hanumaninstitute.Player432hz:~: content-rating-missing
```

Without using `appdata.xml`, it builds fine.

Strangely, the simple presence of `appdata.xml`, even if not referenced from `.conf` file, increases the output from 25MB to 39MB !??

**Comment by kuiperzone** [comment]
It is not clear to me why you are getting an "desktop-app-launchable-missing" error with your project. Although you seem to be using the appdata.xml template, the project config is your own. I cannot repeat that here with the HelloWorld project, nor with my other projects.

I wondered if the AppImageTool package had been updated since I released my code. It doesn't seem to have changed. I'm using a build from 2020-12-31 11:48:33 UTC, or the AppImageTool GitHub release 13.

The "cid-desktopapp-is-not-rdns" warning in your output looks to be caused by the naming of your APP_ID. It should be reverse DNS, ie. use your website name in reverse.

With the default 1.1.1 PublishAppImage HelloWorld, I only get the following "gentle warnings":

    net.example.HelloWorld.appdata.xml
    I: net.example.HelloWorld:11: description-first-para-too-short
       No description available (TBD).
    I: net.example.HelloWorld:~: content-rating-missing

However, I can update the appdata.xml file to make these go away.

**Comment by kuiperzone** [comment]
>desktop-app-launchable-missing TBD

**Comment by kuiperzone** [comment]
For info! Related to?: https://github.com/AppImage/AppImageKit/issues/603

**Comment by kuiperzone** [comment]
Not the only one having this issue, but it now works fine in 1.3.0. See info above.
